[project]
name = "auth"
version = "0.1.0"
requires-python = ">=3.12"

dependencies = [
    "django",
    "celery[redis]",
    "djangorestframework",
    "python-dotenv",
    "django-cors-headers",
    "djangorestframework-simplejwt",
    "firebase-admin>=7.4.0",
    "cryptography",
    "azure-storage-blob",
    "django-push-notifications>=3.3.0",
    "mysqlclient"





]