# Generated by Django 6.0.6 on 2026-06-24 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movies",
            fields=[
                ("Movie_id", models.AutoField(primary_key=True, serialize=False)),
                ("uploader_id", models.BigIntegerField(default=0)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("cast", models.TextField(blank=True, null=True)),
                ("zoner", models.CharField(blank=True, max_length=255, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MovieUrls",
            fields=[
                ("Movie_url_id", models.AutoField(primary_key=True, serialize=False)),
                ("blob_url", models.URLField(max_length=2000)),
                (
                    "Movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="SAS_GENERATOR.movies",
                    ),
                ),
            ],
        ),
    ]
