# Generated by Django 6.0.6 on 2026-06-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SAS_GENERATOR", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="reel",
            field=models.BooleanField(default=False),
        ),
    ]
