# Generated by Django 6.0.6 on 2026-06-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SAS_GENERATOR", "0002_movies_reel"),
    ]

    operations = [
        migrations.AddField(
            model_name="movieurls",
            name="url_for_preview",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
