# Generated by Django 6.0.6 on 2026-07-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SAS_GENERATOR", "0003_movieurls_url_for_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="movieurls",
            name="is_have_plan",
            field=models.BooleanField(default=False),
        ),
    ]
