# Generated by Django 6.0.6 on 2026-07-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SAS_GENERATOR", "0004_movieurls_is_have_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="PREMIUM_USER",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(unique=True)),
                (
                    "user_email",
                    models.EmailField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                ("is_premium", models.BooleanField(default=False)),
                ("premium_start_date", models.DateTimeField(blank=True, null=True)),
                ("premium_end_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
