# Generated by Django 6.0.6 on 2026-07-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100)),
                (
                    "order_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("plan_id", models.CharField(max_length=100)),
                ("payment_id", models.CharField(blank=True, max_length=100, null=True)),
                ("amount", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "CREATED"),
                            ("VERIFIED", "VERIFIED"),
                            ("SUCCESS", "SUCCESS"),
                            ("FAILED", "FAILED"),
                            ("REFUNDED", "REFUNDED"),
                        ],
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subscriptionplan",
            fields=[
                (
                    "plan_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("plan_name", models.CharField(max_length=100)),
                ("price", models.PositiveIntegerField()),
                ("duration", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100, unique=True)),
                ("plan_id", models.CharField(max_length=100)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
