# Generated by Django 6.0.6 on 2026-07-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="user_email",
            field=models.EmailField(default=None, max_length=100),
        ),
    ]
