# Generated by Django 6.0.6 on 2026-07-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0002_payment_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="user_email",
            field=models.EmailField(
                blank=True, default=None, max_length=100, null=True
            ),
        ),
    ]
