# Generated by Django 6.0.6 on 2026-07-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0003_alter_payment_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="user_id",
            field=models.CharField(max_length=100),
        ),
    ]
