name: Celery Worker Video CI
on:

  push:
    branches: [ "dev" ]
    paths:
      - 'CeleryConsumer/**'
      - '.github/workflows/celery-worker-video.yml'
jobs:
  build-celery-worker-video-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./CeleryConsumer
          file: ./CeleryConsumer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/celeryconsumervideo:${{ github.sha }}

      - name: Checkout GitOps Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.GITOPS_REPO }}
          token: ${{ secrets.GITOPS_TOKEN }}
          path: app
      - name: Show files
        run: |
            echo "Current directory:"
            pwd

            echo "Files in workspace:"
            ls -la

            echo "Files in GitOps repo:"
            ls -R app/k8s-files

            
      - name: Update deployment.yaml
        run: |
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/celeryconsumervideo:${{ github.sha }}|" \
          app/k8s-files/celeryconsumer-videos.yml
      - name: Commit and Push
        run: |
          cd app/k8s-files

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add -f .
          git commit -m "Update image tag" || echo "No changes"
          git push 
